name: programmingebook
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  flutter_svg: ^0.17.4
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  http: ^0.12.1
  fancy_bottom_navigation: ^0.3.2
  badges: ^1.1.1
  flutter_swiper: ^1.1.6
  flutter_spinkit: ^4.1.2
  cached_network_image: ^2.2.0+1
  fluttertoast: ^3.1.3
  shimmer: ^1.1.1
  video_player: ^0.10.11+1
  shared_preferences: ^0.5.7+3
  url_launcher: ^5.4.11
  rxdart: ^0.24.1
  sqflite: ^1.3.1
  connectivity: ^0.4.8+6
  permission_handler: ^5.0.1
  auto_size_text: ^2.1.0
  animated_text_kit: ^2.2.0
  pull_to_refresh: ^1.6.0
  logger: ^0.9.1
  event_bus: ^1.1.1
  flutter_mdetect: ^0.0.3
  easy_localization: ^2.3.2
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/svg/
    - resources/langs/en-US.json
    - resources/langs/my.json

  fonts:
  - family: GalleryIcons
    fonts:
      - asset: fonts/GalleryIcons.ttf